
gem 'Craigslist_Area_Job_Search'
gem "nokogiri", ">= 1.10.4"

source "https://rubygems.org"

# Specify your gem's dependencies in Craigslist_Area_Job_Search.gemspec
gemspec

gem 'pry'
gem 'nokogiri', '1.10'
gem 'rspec'